### ISSUE TITLE
stderr maxBuffer exceeded

### ISSUE THREAD

**Issue by rexxars** [nolanlawson/slow-deps#12]
Module names hidden to protect the guilty ;)

```
{ Error: stderr maxBuffer exceeded `npm install '<some-module>@^1.0.39'` (exited with error code undefined)
    at Socket.<anonymous> (child_process.js:287:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
  cmd: 'npm install \'<some-module>@^1.0.39\'',
  stdout: '',
  stderr: 'npm http request GET https://registry.npmjs.org/some-module\nnpm http 200 https://registry.npmjs.org/some-module\nnpm http fetch GET https://registry.npmjs.org/some-module/-/cli-1.0.45.tgz\nnpm http fetch 200 https://registry.npmjs.org/some-module/-/cli-1.0.45.tgz\nnpm http request GET https://registry.npmjs.org/some-check\nnpm http request GET https://registry.npmjs.org/some-module-client\nnpm http request GET https://registry.npmjs.org/some-resolver\nnpm http request GET https://registry.npmjs.org/some-mo
```

Any ideas?

**Comment by nolanlawson** [comment]
This looks like a problem with `child-process-promise`. Arguably I should switch to using a normal Promise shim over `child_process` since I don't care about the stdout output anyway (which is apparently overflowing the buffer).

Knowing which dep logs this much would actually help diagnose. :)
